### ISSUE TITLE
New Core Temporal Adjusters Need Testing

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1147]
There are new temporal adjusters for use with the quantize3 package in the core that need testing.  We should write JUnit tests like the DateUtils tests for these for the 3.3.0 release.

The adjusters are in the com.infiniteautomation.mango.util.datetime package.

**Comment by terrypacker** [comment]
There is a start for a test in com.infiniteautomation.mango.util.datetime.TruncateTimePeriodAdjusterTest

**Comment by Puckfist** [comment]
I got Jared to agree with me about leap day, but we can continue that discussion. Also note that weeks will go back to the adjusted start of the week, meaning the first day of the week of the year, as opposed to Monday always in the original code. I think this makes sense because the weeks are adjusted, too.
