### ISSUE TITLE
When Copying a Data Source the new Device Name field is not used

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#1261]
When I copy a Data Source I see a field called Device Name and Name.  I would expect the Data Points would be created using the Device Name but their Device Name is set from the Name field.

**Comment by terrypacker** [comment]
This is because the Device Name is never passed through to the DataSourceDwr.finishCopy() method.  To fix this we should:
1.  Fix the Legacy UI to pass in the Device Name
2. Supply the Device Name to the DataSourceDao.copyPoints() method
3. Fix the Rest API to allow a Device Name to be supplied when copying the data source.

**Comment by terrypacker** [comment]
Added changes 1-3.  Tested and working.  Probably should poke around a little more on the page to make sure nothing else is affected but the changes were minor.  So long as nothing else calls the DataSourceDwr.finishCopy method we should be good.

**Comment by Puckfist** [comment]
Nothing does
