### ISSUE TITLE
H2 database grows significantly from persistent TCP syncs

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1291]
On at least one system where the mah2.h2.db file is growing until the disk is consumed, the cause appears to be that PersistentSendThread 447 where ot saves the start times frequently during a sync. This was observed to increase the size of the database without it reusing that space on subsequent updates.  PublisherDao.savePersistentData is definitely not raising an audit event, so where the space goes, nobody knows

**Comment by Puckfist** [comment]
This seemed related: https://groups.google.com/forum/#!topic/h2-database/eXBzpF4WnNk

The INFORMATION_SCHEMA.LOG_DATA does seem to have a few hundred more entries each time I run this publisher. No sure why they aren't getting removed, though.

**Comment by terrypacker** [comment]
I have created H2SizeBugTest in the core to demonstrate the problem and I intend to create an even simpler case that we can submit to H2.  I have tried multiple configuration settings with both PageStore and MVStore with no luck.  

-  Some things I've noticed, if you update the column with the same value there is no size change.  
-  If you delete the row and insert a new one with a null value, then update it with the blob value there is no size change.
-  The bug seems to only occur when updating a column with a new blob value.
-  The bug is NOT in our Dao layer as I wrote a section of the test to run JDBC commands only and it still happens.
-  The overall size can be reduced by 10x during runtime and compaction at shutdown actually works if the column type is BINARY [http://www.h2database.com/html/datatypes.html#binary_type](http://www.h2database.com/html/datatypes.html#binary_type)

I suggest we change all the LONGBLOB column types to BINARY and submit an issue to H2.

**Comment by terrypacker** [comment]
One more note is that we can use this in an upgrade script to alter the columns:

```
ALTER TABLE publishers ALTER COLUMN rtdata BINARY;
```

This will only change the datatype and leave the NOT NULL requirement if there is one.

**Comment by terrypacker** [comment]
Columns that are to be modified:

templates.data
dataSources.data
dataSources.rtdata
dataPoints.data
eventHandlers.data
publishers.data
publishers.rtdata

**Comment by Puckfist** [comment]
I solved this on the module's side as well by using a separate table: https://github.com/infiniteautomation/ma-modules-private/commit/f1d53630ca9992cd96d6a757daaba96bf2592ec0

**Comment by terrypacker** [comment]
The commit to change column types has been reverted.  When H2 1.4.198 is released we should test to see if it will work as there is a but in 1.4.197 that is preventing us from starting up on older versions of the database on the 2nd startup.

**Comment by Puckfist** [comment]
This issue as named is solved and can be closed, I think

**Comment by terrypacker** [comment]
Agreed, there is still the general LOB growth problem that will need to be dealt with but should be addressed in a separate issue.
