### ISSUE TITLE
RealTimeDataPointValueCache.getUserView() does not honor data source edit permission

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1312]
If you have edit permission to a data source but not read/set permissions to a data point you will not see it in the list of points returned from RealTimeDataPointValueCache.getUserView().

RealTimeDataPointValue should be updated so it can return the DataPointVO and then we can just use Permissions.hasDataPointReadPermission().

There is also another issue in that if RealTimeDataPointValue.initialize() is called the properties such as readPermission etc are not updated. All the getters should be updated to just get the value from the VO instead of storing them inside RealTimeDataPointValue.

**Comment by terrypacker** [comment]
Some notes:

1.  The path member of the RealTimeDataPointValue is ok because the parent cache is reset if the hierarchy changes.
2.  Review the getTags() method
3.

**Comment by terrypacker** [comment]
The permissions issue is fixed as the cascading call starting at this line in `RealTimeDataPointValueCache.getUserView(User user)`

```
        //Filter on permissions
        for (RealTimeDataPointValue rtdpv : this.realTimeData) {
            if(Permissions.hasDataPointReadPermission(user, rtdpv.vo))
                results.add(rtdpv);
        }
```

Does end up checking for both the Global Data Source and specific Data Source edit permissions.

I believe the `RealTimeDataPointValue.pointInitialized()` part of this issue is now fixed by replacing the VO when the point is initialized and then loading the tags on demand when called.
