### ISSUE TITLE
Event handler script validation doesn't include additional context objects

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1473]
When event handler scripts run, whether Set Point Handler or Email Handler, they are given the EventInstance as evt and the EventInstanceWrapper as event.

Email handlers are also given the whole FTL model under the key 'model', and UNCHANGED is wrapped in as 'CANCEL' for a way to prevent sending the email

**Comment by terrypacker** [comment]
What are you suggesting as the solution?  To provide some dummy data in the model during validation?

**Comment by Puckfist** [comment]
Yeah, that would be my first thought. TestEventInstance and TestEventInstanceWrapper

I think because we allow handlers on multiple event types that may be as good as it gets.

**Comment by terrypacker** [comment]
There are 2 ways to solve this since the validation uses the common `/v2/script/validate` endpoint:

1.  Expose another field in MangoJavaScriptModel that allows the page to supply some 'additional context' objects to the script.  Then perform the logic on the page.

2.  Create a new endpoint for the validation of these and add the additional context objects in the backend.

**Comment by terrypacker** [comment]
I'm leaning towards 1 as it would allow the UI developer to provide inputs for the dummy values in any context object so the user could test against desired data.
