### ISSUE TITLE
is  pointvalues table dataType filed  nessary? this  is redundancy and use disk  space

### ISSUE THREAD

**Issue by kongdongshan** [infiniteautomation/ma-core-public#1636]
pointvalue's datatype  is decide by datapointVo,one certain datapoint have one certain pointvalue type,if it is nessary,it can be remove,much more dataype is same value "3".

**Comment by terrypacker** [comment]
This field is there so that when extracting data from the pointValues table we don't have to `JOIN` on the dataPoints table.  This way we can convert the point value data into the correct data type and use a single column `pointValue` to store the data instead of having a column for each data type.  It is arguable that it is the most performant way to achieve this.  But we have the Mango NoSQL module for high performance and storage optimization.
