### ISSUE TITLE
Add ability to export and import from a text file on the import/export page

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#196]

**Comment by Puckfist** [comment]
This is a feature of the new UI's import/export page.

**Comment by Puckfist** [comment]
The feedback provided by the importer could be better. For instance, I had a massive document I was trying, but got no feedback whatsoever. I checked the console, had exceptions printed about an unexpected character, a "," at the end of my data points list. So, it's more particular than serotonin json because it is using jackson? I removed this comma and it worked, but there was no way to know the comma was the problem just using the importer.

**Comment by terrypacker** [comment]
The REST endpoint uses Serotonin JSON so we should be able to get the feedback onto the page.  I'll do some further testing to see if it is the backend not providing the information or the frontend just not displaying it.

**Comment by terrypacker** [comment]
I  found that when uploading a file via the new UI a POST is made to the /rest/v1/json-emport endpoint that expects a serotonin JsonValue object.  If the JSON isn't valid Jackson JSON (which is stricter) the call will fail.  We have 2 options here:

1.  POST the file to the /rest/v1/json-emport/upload-file endpoint
2.  Change the existing endpoint to accept a String and then let Serotonin JSON convert that into a JsonValue

Probably should do 2 no matter what, but will wait to discuss with the UI team.

**Comment by jazdw** [comment]
Why are we trying to work around people supplying incorrect JSON? We should just show the error.

**Comment by jazdw** [comment]
Another thing to note is when doing an import, no status is displayed until the import completes. We will need to fix this.
