### ISSUE TITLE
Adding of custom code snippets to page template for web analytics packages

### ISSUE THREAD

**Issue by jeremyjhall** [infiniteautomation/ma-core-public#302]
Most web analytics packages <i>(google analytics, etc.)</i> require a few lines of custom code to be inserted into the page HTML before the closing head or body tag. It could look like so:

![screen shot 2014-11-16 at 7 44 48 pm](https://cloud.githubusercontent.com/assets/1190351/5061283/4b10e8ee-6dc9-11e4-906c-3bd5e3f2935f.png)

**Comment by Puckfist** [comment]
I like!

The only modification I offer for consideration is adding a note in the help document about Mango's web folder being its webapp root, so people know you can do things like...

Insert before closing body:
<script type="text/javascript" src="myUselessAlert.js"/>

and make mango/web/myUselessAlert.js :
alert("It Works!");

**Comment by Puckfist** [comment]
Uh-oh, bad behavior. Using the script in the previous example, reloading the system settings page yields a tab character or two in the text field for what to insert instead of the proper html tags to insert. Doesn't seem to happen if I use:
<script type="text/javascript">alert("It Works!");</script>

**Comment by terrypacker** [comment]
This is because that script failed on a load and killed the javascript for the page, presumably because you didn't have the file in the web folder?  This is one problem with this feature, its quite dangerous as you can kill all the pages for Mango.

I've added a filter so that the analytics content is NOT added on the system settings page, so if you do completely mess it up you can still change it back.

**Comment by Puckfist** [comment]
Perhaps we should tell people not to use that style of html tag (self-closed), as that example I presented breaks the users and new data point details pages. However, when I convert it to &lt;script&gt;&lt;/script&gt; all is well.

I also discovered it was not being loaded on the Internal metrics page, the login page (nor DGLux login), page not found page, and the system settings page. It makes perfect sense to me to not have it on the system settings page, in case you bork things and prevent other pages from loading. Similarly I could understand it not being on the login page.

As to other modules, I didn't see it on the Brewer's Dashboard page, or the custom dashboard pages. I do not have every module installed at this instance to check, but I will not close this issue until I have clicked them all.

**Comment by terrypacker** [comment]
The analytics are inserted on every page that uses the JSP page tag, which is pretty much all Mango pages that are rendered via JSP.  

The reason for your problems with a <script /> tag is because that is not valid syntax, <script></script> is required for those.

It is loaded on the internal metrics page as far as I can tell.

**Comment by Puckfist** [comment]
The internal metrics page mapped my included script to its root, /internal/myUselessAlert.js

The problem was fixed by adding a leading / to the src path, so I would think we should put that / in the help document too.

**Comment by terrypacker** [comment]
That has now been added.
