### ISSUE TITLE
Add Validation button to the Ascii file reader data source so you can test the regex

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#313]

**Comment by Puckfist** [comment]
It seems well behaved, but it's only displaying points that matched the identifier at least. I think that's fine behavior. I also noticed it displays a PointValueTime(VALUE@TIME) in the value column. I understand this is because the timestamp can be set in the point, so this seems good enough, but perhaps it's more user friendly to have a value and a time column. Who can say.
