### ISSUE TITLE
Long Running Requests block data sources

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#337]
Long API requests block data sources - WARN  2015-02-03 16:48:13,880 (com.serotonin.m2m2.rt.dataSource.PollingDataSource.scheduleTimeout:106) - Dashboard Demo: poll at 2015/02/03 16:48:12 aborted because a previous poll started at 2015/02/03 16:48:12 is still running

**Comment by terrypacker** [comment]
This may be fixable by moving spring to use Asyc type requests through Jetty instead of the current synchronous methodology.

**Comment by mlohbihler** [comment]
This behaviour is by design. It was deemed undesirable to have a device polled multiple times simultaneously, especially since some data sources will block requests behind each other causing outstanding requests to pile up. The message is intended as an indication that the polling rate on the data source is too high.

**Comment by jazdw** [comment]
The issue is that long running REST API calls are blocking the data sources somehow. The API calls are unrelated to the data sources, we are just retrieving point values from the database. It may be that the contention is occurring at the database layer.

**Comment by terrypacker** [comment]
This should be checked on a graphical view page that access a high polling virtual data point logging into the NoSQL database.

**Comment by terrypacker** [comment]
Closing as this doesn't seem to be happening anymore in any of my tests.
