### ISSUE TITLE
Internationalization isn't working properly.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#40]
Unable to change language.

**Comment by jazdw** [comment]
@terrypacker 
I was just looking at how to retrieve the Mango language setting for doing some i18n on the front end and noticed that changing the language setting doesn't seem to work at all. Perhaps we broke something in 2.8.x? @Puckfist gets an icon on the menu bar which isnt showing for me from where he can switch the language but its not retained across a restart.

Also there are various locations that call Translations.getTranslations() without a locale, this calls Locale.getDefault() instead of Common.getLocale() which could cause issues.

Another thing to add is that the REST API currently retrieves the translations for the browsers locale setting instead of the system setting. I would like to see an option for each user to set their language, which would also include an option to use the browser language. Likewise the user should be able to set their timezone to browser timezone.

**Comment by Puckfist** [comment]
That icon on the menu bar doesn't seem to exist on the html5 pages

**Comment by jazdw** [comment]
> Also there are various locations that call Translations.getTranslations() without a locale, this calls Locale.getDefault() instead of Common.getLocale() which could cause issues.

Fixed this in 71506e0528cda4c4d024a19d66ca4b768f707bd0, it should only be used in locations where the DB layer is not initialized, i.e. console output and startup servlet.

Also changed the default language for Mango to the JVMs locale. This does not affect translations as all our default translations do not specify a language (i.e. they are i18n.properties not i18n_en.properties).

**Comment by terrypacker** [comment]
There is a bug in the header JSP code for legacy pages that will only show the language drop down chooser if you have **more than** 1 language pack installed.

**Comment by terrypacker** [comment]
Also in MiscDwr when you set the Language it is a global setting for all users and only for that run of Mango.  Agreed, this should be on a per User basis and saved in the user.

**Comment by jazdw** [comment]
This is partially fixed, the user now has a locale field and the REST requests use this but there are plenty of areas where the wrong language will be used.

**Comment by terrypacker** [comment]
Closing as this is being handled in the new UI and is too broad an issue to track all the internationalization quirks.
