### ISSUE TITLE
Static html/shtm files not rendering with Content-Type set.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#470]
Not exactly sure why but the Spring interface org.springframework.web.servlet.View is not adding the Content-Type header into the response for the Custom Dashboards module.  This has been fixed in this commit infiniteautomation/ma-modules-private@6ff3dccd59f908e20dae4cc1f8ba5833f097d241

But we need to verify any other problems like this that might arise, a quick review of where we use the View interface (although not all apply to this problem):

* Custom Dashboards
* DGLux
* Graphical Views
* JSP Views
* Reports
* SQL Console
* Watchlist
* Core

**Comment by terrypacker** [comment]
Fixed Reports here: infiniteautomation/ma-modules-public@5dba2dbf05d432a252cb32e663577c14ec284b04

**Comment by Puckfist** [comment]
Custom Dashboards, Graphical Views, Reports, SQL Console, Watchlist and the core seem to be behaving. and i'm about to make a new issue for JSP Views...

I haven't tested DGLux (since it is flash and doing its own stuff in the DWR for its module, it seems fairly safe to assume this shouldn't affect it. I have confirmed the .swf still loads).

**Comment by Puckfist** [comment]
The JSP Views item, [this issue](https://github.com/infiniteautomation/ma-core-public/issues/497), was unrelated and resolved.

**Comment by Puckfist** [comment]
Everything is seemingly working
