### ISSUE TITLE
Excel Reports - Validation says success, report instance says failure

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#491]
If something goes wrong in the filling out of the excel template, the validation message can still say success even if running the report failed. To evince, use the demo templates in the excel module and only add one point assigned to an invalid field. Run the report and watch the top of the page. You should see a green validation saying "Success!" but if you click to run reports it will have failed.

**Comment by terrypacker** [comment]
We will need to discuss this further.  Since reports are run in the background the 'Success' you are seeing is that the report has been scheduled and run in the background.  We won't know it has failed until it actually runs, which is after the REST call to run the report has returned.  One option would be to display a message that says 'Scheduled' or 'Running' instead of Success.

**Comment by terrypacker** [comment]
Is this important or should we close it?

**Comment by terrypacker** [comment]
Change to 'Scheduled'

**Comment by Puckfist** [comment]
The new UI says "Running"
