### ISSUE TITLE
Popup on importing before overwriting items

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#50]
Rather than overwriting items automatically on import Mango should pop up and let the user confirm that you want to overwrite this one or all or no to this one or no to all.  Mango should still import things that don't exist.  This can be use on the Template Importer but for the auto import from the JSON file it needs to automatically override all so each module probably needs to have the option weather it will use the check or not.

**Comment by terrypacker** [comment]
Saved vs. Added feedback is already provided.  Closing this issue since it is not possible/reasonable to provide feedback during the import since it runs in the background.  Feel free to open new issues around 2 potential features:

1.  Provide feedback that includes what items were imported but not changed
2. A checkbox that would indicate you only want to import new items and leave existing items unchanged
