### ISSUE TITLE
Virtual Data Source Point Locator Models - Missing Members

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#505]
Many of the members were labeled as JsonIgnore  this has been changed and needs testing.  When ready put new module in store.

**Comment by Puckfist** [comment]
An exported virtual point will lose all the state information for all the other change types previously configured on the point. It will correctly import the current change type and information that never conflicts in any change type (AttractorPointXID, for instance, is used in only 1 change type and will not change). This strikes me as acceptable behavior, since the relevant change type configuration is the part exported or imported.
