### ISSUE TITLE
MangoNoSQL - Corruption Scan Progress Updates

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#822]
For very long running corruption scans it would be ideal to see how far along in the process we are.  Something to the effect of: x out of y total directories scanned.

**Comment by Puckfist** [comment]
Closing this as no long relevant. Since the style of corruption scanning switched to live scanning, you can't have a count for how many things there are to be corruption scanned as it happens individually. It would probably be possible for manually triggered corruption scans, but those are not so common anymore. Now this information will probably manifest (at least during startup) as the count of which data source has been enabled of the total number of enabled data sources. Anyway, closing.
