### ISSUE TITLE
Database Upgrade Test

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#873]
Upgrade DB's from 2.7.10,2.7.12 and the latest 2.6 releases to ensure the scripts run without error.

**Comment by Puckfist** [comment]
This seems like it should be the last issue to close.

**Comment by terrypacker** [comment]
Make sure there are legacy Event Detectors in the legacy database.

**Comment by Puckfist** [comment]
Well, several months later it turns out there was an issue for MySQL conditionally dropping the tags column if there were multiple databases of different versions on the same MySQL server, and more importantly that event detectors came unlinked if their IDs had gaps in them, since the ID from the pointEventDetector table (eventTypeRef2) was not maintained.
